<!DOCTYPE html>
<html lang="en">
	<head>
		<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
		<meta charset="utf-8" />
		

		<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0" />

[if:"[var:"useajax-var"end var]","


		<!--[if !IE]> -->
		<link rel="stylesheet" href="/template/Ace1.3.3/assets/css/pace.css" />

		<script data-pace-options='{ "ajax": true, "document": true, "eventLag": false, "elements": false }' src="/template/Ace1.3.3/assets/js/pace.js"></script>

		<!-- <![endif]-->
"end if]
		<!-- bootstrap & fontawesome -->
		<link rel="stylesheet" href="/template/Ace1.3.3/assets/css/bootstrap.css" />
		<link rel="stylesheet" href="/template/Ace1.3.3/assets/css/font-awesome.css" />

		<!-- text fonts -->
		<link rel="stylesheet" href="/template/Ace1.3.3/assets/css/ace-fonts.css" />
<link rel="stylesheet" href="/template/Ace1.3.3/assets/css/colorbox.css" />
<link rel="stylesheet" href="/template/Ace1.3.3/assets/css/jquery-ui.custom.css" />
<link rel="stylesheet" href="/template/Ace1.3.3/assets/css/chosen.css" />
<link rel="stylesheet" href="/template/Ace1.3.3/assets/css/datepicker.css" />
<link rel="stylesheet" href="/template/Ace1.3.3/assets/css/bootstrap-timepicker.css" />
<link rel="stylesheet" href="/template/Ace1.3.3/assets/css/daterangepicker.css" />
<link rel="stylesheet" href="/template/Ace1.3.3/assets/css/bootstrap-datetimepicker.css" />
<link rel="stylesheet" href="/template/Ace1.3.3/assets/css/colorpicker.css" />
<link rel="stylesheet" href="/template/Ace1.3.3/assets/css/fullcalendar.css" />
<link rel="stylesheet" href="/template/Ace1.3.3/assets/css/jquery.gritter.css" />
<link rel="stylesheet" href="/template/Ace1.3.3/assets/css/ace-skins.css" />


[if:"[var:"lng_CH-sess-var"end var]=='ar'","
<link rel="stylesheet" href="/template/Ace1.3.3/assets/css/ace-rtl.css" />
"end if]
<style>
    .iconleftx {
    width: 35px;
    float: inherit;
    height: 34px;
    padding: 10px 0px 0px 0px;
    display: none;
}
@media (min-width: 768px){ 
.iconleftx {
    display: block;
}
}
.modal-body {
    max-height: 400px;
    overflow-y: auto;
    overflow-x: hidden;
}
.form-horizontal .form-group {
    margin-left: 0px;
    margin-right: 0px;
}
</style>
<script src="/template/Ace1.3.3/assets/js/jquery.js"></script>




		<!-- ace styles -->
		<link rel="stylesheet" href="/template/Ace1.3.3/assets/css/ace.css" class="ace-main-stylesheet" id="main-ace-style" />

		<!--[if lte IE 9]>
			<link rel="stylesheet" href="/template/Ace1.3.3/assets/css/ace-part2.css" class="ace-main-stylesheet" />
		<![endif]-->

		<!--[if lte IE 9]>
		  <link rel="stylesheet" href="/template/Ace1.3.3/assets/css/ace-ie.css" />
		<![endif]-->

		<!-- ace settings handler -->
		<script src="/template/Ace1.3.3/assets/js/ace-extra.js"></script>

		<!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->

		<!--[if lte IE 8]>
		<script src="/template/Ace1.3.3/assets/js/html5shiv.js"></script>
		<script src="/template/Ace1.3.3/assets/js/respond.js"></script>
		<![endif]-->
	</head>

	<body class="[var:"skin"end var] [style-rtl]">
            
            