


lezaz~time() <br>
------------lezaz----------------------<hr><br>
lezaz~date(d/m/Y,555666999) // for function call and echo result  its mean  func(parm1,parm2) <br>
lezaz#id // echo value for lezaz syntax use id  its mean $lezaz_id<br>
lezaz#id[parm] // echo value for lezaz syntax use id parameter  its mean  $lezaz_id_parm<br>
lezaz$parm // echo $parm from php files  its mean $parm <br>
lezaz$parm1[item] // echo array item from $parm using in php files  its mean $parm[item] <br>
lezaz:get(parm) // echo result from lezaz class its mean $lezaz->func(parm)<br>
<br>
  
<lezaz:if id='ififx' condition="lezaz#id[parm]" result="yes,no"  PRINT='dddc'/><br>    
#ififx: lezaz#ififx <br>
<lezaz:for id="idfor" from='3' condition='$i<lezaz:get(bass)' to='27' step='1' print='false'> lezaz#idfor <br> </lezaz:for><br> 
 

lezaz:get(bass)bbbbb  cc