



------------lezaz----------------------<hr><br>
lezaz~date(dd/mm/Y,666655544) // for function call and echo result  its mean  func(parm1,parm2) <br>
lezaz#id // echo value for lezaz syntax use id  its mean $lezaz_id<br>
lezaz#id[parm] // echo value for lezaz syntax use id parameter  its mean  $lezaz_id_parm<br>
lezaz$parm // echo $parm from php files  its mean $parm <br>
lezaz$parm1[item] // echo array item from $parm using in php files  its mean $parm[item] <br>
lezaz:get(parm) // echo result from lezaz class its mean $lezaz->func(parm)<br>
<br>
 
<lezaz:if id='ififx' condition="1==1" result="yes,no" print="false"/><br>
#ififx: lezaz#ififx <br>
<lezaz:for id="id" from="1" to="10" step="-2"> lezaz#id </lezaz:for><br>
