
<ul class="nav nav-list">






    <li class="lezaz:set(index)">
        <a href="/{{ajxurl}}index">
            <i class="menu-icon fa fa-tachometer"></i>
            <span class="menu-text"> [Dashboard] </span>
        </a>

        <b class="arrow"></b>
    </li> 



    <lezaz:menu id="1" text="Scope" url="1" icon="" text-icon="1"></lezaz:menu>
    <lezaz:menu id="2" text="Normative references" url="2" icon="" text-icon="2"></lezaz:menu>
    <lezaz:menu id="3" text="Terms and definition" url="3" icon="" text-icon="3"></lezaz:menu>

    <lezaz:menu id="4" text="Context of the organization" url="4" icon="" text-icon="4">
        <lezaz:menu id="41" text="Organization context" url="41" icon="" text-icon="4.1"></lezaz:menu>
        <lezaz:menu id="42" text="needs & expectations" url="42" icon="" text-icon="4.2"></lezaz:menu>
        <lezaz:menu id="43" text="Scope of the OH&S" url="43" icon="" text-icon="4.3"></lezaz:menu>
        <lezaz:menu id="44" text="Oh&S management system" url="44" icon="" text-icon="4.4"></lezaz:menu>
    </lezaz:menu>

    <lezaz:menu id="5" text="Leadership" url="5" icon="" text-icon="5">
        <lezaz:menu id="51" text="Leadership & commitment" url="51" icon="" text-icon="5.1"></lezaz:menu>
        <lezaz:menu id="52" text="Policy" url="52" icon="" text-icon="5.2"></lezaz:menu>
        <lezaz:menu id="53" text="Roles & authorities" url="53" icon="" text-icon="5.3"></lezaz:menu>
    </lezaz:menu>

    <lezaz:menu id="6" text="Planning" url="6" icon="" text-icon="6">
        <lezaz:menu id="61" text="Action & opportunities" url="61" icon="" text-icon="6.1">
            <lezaz:menu id="611" text="General" url="611" icon="" text-icon="6.1.1"></lezaz:menu>
            <lezaz:menu id="612" text="Hazard identification" url="612" icon="" text-icon="6.1.2"></lezaz:menu>
            <lezaz:menu id="613" text="Determination of legal" url="613" icon="" text-icon="6.1.3"></lezaz:menu>
            <lezaz:menu id="614" text="Assessment of risks" url="614" icon="" text-icon="6.1.4"></lezaz:menu>
            <lezaz:menu id="615" text="Planning for change" url="615" icon="" text-icon="6.1.5"></lezaz:menu>
            <lezaz:menu id="616" text="Planning to take action" url="616" icon="" text-icon="6.1.6"></lezaz:menu>
        </lezaz:menu>
        <lezaz:menu id="62" text="OH&S objectives" url="62" icon="" text-icon="6.2"></lezaz:menu>
    </lezaz:menu>


    <lezaz:menu id="7" text="Support" url="7" icon="" text-icon="7">
        <lezaz:menu id="71" text="Resources" url="71" icon="" text-icon="7.1"></lezaz:menu>
        <lezaz:menu id="72" text="Competence" url="72" icon="" text-icon="7.2"></lezaz:menu>
        <lezaz:menu id="73" text="Awareness" url="73" icon="" text-icon="7.3"></lezaz:menu>
        <lezaz:menu id="74" text="Information & consultation" url="74" icon="" text-icon="7.4"></lezaz:menu>
        <lezaz:menu id="75" text="Documented" url="75" icon="" text-icon="7.5"></lezaz:menu>
    </lezaz:menu>

    <lezaz:menu id="8" text="Operations" url="8" icon="" text-icon="8">
        <lezaz:menu id="81" text="Operational planning & control" url="81" icon="" text-icon="8.1">
            <lezaz:menu id="811" text="General" url="811" icon="" text-icon="8.1.1"></lezaz:menu>
            <lezaz:menu id="812" text="Hierarchy of control" url="812" icon="" text-icon="8.1.2"></lezaz:menu>
        </lezaz:menu>    
        <lezaz:menu id="82" text="Management of change" url="82" icon="" text-icon="8.2"></lezaz:menu>
        <lezaz:menu id="83" text="Outsourcing" url="83" icon="" text-icon="8.3"></lezaz:menu>
        <lezaz:menu id="84" text="Procurement" url="84" icon="" text-icon="8.4"></lezaz:menu>
        <lezaz:menu id="85" text="Contractors" url="85" icon="" text-icon="8.5"></lezaz:menu>
        <lezaz:menu id="86" text="Emergency & response" url="86" icon="" text-icon="8.6"></lezaz:menu>
    </lezaz:menu>
  
 
    <lezaz:menu id="9" text="Performance evaluation" url="9" icon="" text-icon="9">
        <lezaz:menu id="91" text="Monitoring" url="91" icon="" text-icon="9.1">
            <lezaz:menu id="911" text="General" url="911" icon="" text-icon="9.1.1"></lezaz:menu>
            <lezaz:menu id="912" text="Evaluation of compliance" url="912" icon="" text-icon="9.1.2"></lezaz:menu>
        </lezaz:menu> 
        <lezaz:menu id="92" text="Internal audit" url="92" icon="" text-icon="9.2">
            <lezaz:menu id="921" text="Objective" url="921" icon="" text-icon="9.2.1"></lezaz:menu>
            <lezaz:menu id="922" text="Process" url="922" icon="" text-icon="9.2.2"></lezaz:menu>
        </lezaz:menu>
        <lezaz:menu id="93" text="Management review" url="93" icon="" text-icon="9.3"></lezaz:menu>
    </lezaz:menu>  

    <lezaz:menu id="10" text="Improvement" url="10" icon="" text-icon="10">
        <lezaz:menu id="101" text="Incident & corrective action" url="101" icon="" text-icon="10.1"></lezaz:menu>
        <lezaz:menu id="102" text="Continual improvement" url="102" icon="" text-icon="10.2"></lezaz:menu>
    </lezaz:menu>



    <li class='lezaz:set(add_member_m) lezaz:set(managment_members_m)'>
        <a href="#" class="dropdown-toggle">
            <i class="menu-icon fa fa-list"></i>
            <span class="menu-text"> [members] </span>

            <b class="arrow fa fa-angle-down"></b>
        </a>

        <b class="arrow"></b>

        <ul class="submenu">
            <li class="lezaz:set(add_member)">
                <a href="/{{ajxurl}}add_member">
                    <i class="menu-icon fa fa-caret-right"></i>
                    [add member]
                </a>

                <b class="arrow"></b>
            </li>

            <li class="lezaz:set(managment_members)">
                <a href="/{{ajxurl}}managment_members">
                    <i class="menu-icon fa fa-caret-right"></i>
                    [manage members]
                </a>

                <b class="arrow"></b>
            </li>
        </ul>
    </li>

</ul><!-- /.nav-list -->
