
				<ul class="nav nav-list">
                                    
  
                                    
                                  
                                    
                                    
					<li class="lezaz:set(index)">
						<a href="/{{ajxurl}}index">
							<i class="menu-icon fa fa-tachometer"></i>
							<span class="menu-text"> [Dashboard] </span>
						</a>

						<b class="arrow"></b>
					</li> 
                                        
                                        
  lezaz:set(Main_Menu)
  
					

                                        
                                      
					<li class='lezaz:set(add_member_m) lezaz:set(managment_members_m)'>
						<a href="#" class="dropdown-toggle">
							<i class="menu-icon fa fa-list"></i>
							<span class="menu-text"> [members] </span>

							<b class="arrow fa fa-angle-down"></b>
						</a>

						<b class="arrow"></b>

						<ul class="submenu">
							<li class="lezaz:set(add_member)">
								<a href="/{{ajxurl}}add_member">
									<i class="menu-icon fa fa-caret-right"></i>
									[add member]
								</a>

								<b class="arrow"></b>
							</li>

							<li class="lezaz:set(managment_members)">
								<a href="/{{ajxurl}}managment_members">
									<i class="menu-icon fa fa-caret-right"></i>
									[manage members]
								</a>

								<b class="arrow"></b>
							</li>
						</ul>
					</li>

				</ul><!-- /.nav-list -->
