<!-- #section:settings.box -->
<div class="ace-settings-container" id="ace-settings-container">
    <div class="btn btn-app btn-xs btn-warning ace-settings-btn" id="ace-settings-btn">
        <i class="ace-icon fa fa-paperclip bigger-130"></i>
    </div>

    <div class="ace-settings-box clearfix" id="ace-settings-box">
        <div class="[style-pullen] width-50">

            <div class="ace-settings-item">
                <a class="lbl" href='#'> Related procedure</a>
            </div>

            <div class="ace-settings-item">
                <a class="lbl" href='#'> Related standard</a>
            </div>

            <div class="ace-settings-item">
                <a class="lbl" href='#'> Related legislation</a>
            </div>
            <div class="ace-settings-item">
                <a class="lbl" href='#'> Related forms</a>
            </div>

        </div><!-- /.[style-pullen] -->


    </div><!-- /.ace-settings-box -->
</div>
<!-- /.ace-settings-container -->
