<lezaz:form id='bassam' type='setting'>
    fdsggfds gf gdfs gds g
                <lezaz:input use='bassam' type='text' id="instagram" label="[instagram]" placeholder="http://site.com" size-label='2' size='10'  space='12'/> 
            <lezaz:input use='bassam' type='text' id="youtube" label="[youtube]" placeholder="http://site.com" size-label='2' size='10'  space='12'/> 
            <lezaz:input use='bassam' type='text' id="rinning" label="[rinning]" placeholder="http://site.com" size-label='2' size='10'  space='12'/> 
g fdsg df gdfg df
       <lezaz:input use='bassam' id='savenow' value='yes' type='submit' label='[save]' icon='fa-check' color='info'/>
                     <lezaz:input type='reset' label='[reset]' icon='fa-undo' />              
</lezaz:form>
  
   lezaz:msg()
<lezaz:form id='rasha' type='setting'>
   <lezaz:input type='text' id="address" label="[address]-[english]" placeholder="saudi , makka 12 building" size-label='2' size='10'  space='12'/> 
            <lezaz:input type='text' id="addressar" label="[address]-[arabic]" placeholder="saudi , makka 12 building" size-label='2' size='10'  space='10'/> 

     
<lezaz:input type="file" id="logo1" label="[site_logo_up]" size-label='2' size='10'  space='10' />
<lezaz:input type="image" id="logo2" label="[site_logo_down]" size-label='2' size='10'  space='10' />
       <lezaz:input type='submit' label='[save]' icon='fa-check' color='info'/>
                    <lezaz:input type='reset' label='[reset]' icon='fa-undo' />              
</lezaz:form>  