   <lezaz:input 
       
          bassam
       
          
          
              
       
       type   =   "te\"\"\"gfdgfd"       xt   id="site_title" label="[site_titl\"e]-[english]" placeholder="Enter title" size-label='2' size='10'  space='12'/> 

<hs d="dfsf" rssf='fdds ' />fd sfds fds 1111
<jxj dsf='fsdfds' fdfds='fsdf' cdsds="fdsf>f sdfs<fsdf/>" >    
   fdsfdsf dsafdsaf 2222
   fd saf dsfsda2222
       <lezaz:input type='text' ff_-.id="site_ti<?php echo "hi man "; ?>tle" label="[site_title]-[english]" placeholder="Enter title" size-label='2' size='10'  space='12'   > 
       <lezaz:input type='text' ff_-.id="site_title" label="[site_title]-[english]" placeholder="Enter title" size-label='2' size='10'  space='12'   > 
       <lezaz:input type='text' ff_-.id="site_title" label="[site_title]-[english]" placeholder="Enter title" size-label='2' size='10'  space='12'   > 
           xxxxfddsgds33333
           <lezaz:input type='text' ff_-.id="site_title">
               inside to input 1 
           </lezaz:input>
           
                <lezaz:input type='text' ff_-.id="site_title">
               inside to      <lezaz:input type='text' ff_-.id="site_title">
               inside to      <lezaz:input type='text' ff_-.id="site_title">
               inside to      <lezaz:input type='text' ff_-.id="site_title">
               inside to input 1 
           </lezaz:input> 1 
           </lezaz:input> 1 
           </lezaz:input> 1 
           </lezaz:input>
           
                <lezaz:input type='text' ff_-.id="site_title">
               inside to input 1 
           </lezaz:input>
           
           <hs d="dfsf" rssf='fdds ' />fd sfds fds 4444443
       mxxxxx</lezaz:input></lezaz:input></lezaz:input>

</jxj>
<div></div >
    <lezaz:input type='text' id="site_title" label="[site_title]-[english]" placeholder="Enter title" size-label='2' size='10'  space='12'/> 
<hsd d="dfsf" rssf='fdds ' />fd sfds fds 555555

