<!DOCTYPE html>

<html lang="en">
<head><meta charset="utf-8" /><meta name="viewport" content="width=device-width, initial-scale=1.0" /><title>
	Gulf Future Energy
</title><link rel="shortcut icon" href="{{this}}files/GFELogoIcon.ico" type="image/x-icon" /><link rel="icon" href="{{this}}files/GFELogoIcon.ico" type="image/ico" />
<script src="{{this}}files/bundel.js"></script>
 
<script src="{{this}}files/jquery-1.11.1.min.js"></script>
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
    <script type="text/javascript" src="http://code.jquery.com/jquery-latest.min.js"></script>
    <script src="{{this}}files/jquery.zweatherfeed.js" type="text/javascript"></script>
    <script src="{{this}}files/zebra_datepicker.js"></script>
    <script src="{{this}}files/jquery.js"></script>
    <script src="{{this}}fancybox/jquery.fancybox.pack.js"></script>
    <link href="{{this}}fancybox/jquery.fancybox.css" rel="stylesheet" />
    <link href="{{this}}files/font-awesome.min.css" rel="stylesheet" /><link href="{{this}}files/jquery-te-1.4.0.css" rel="stylesheet" /><link rel="stylesheet" href="{{this}}files/weather.css" /><link href="{{this}}files/css.css" rel="stylesheet"/>
<link rel="stylesheet" href="{{this}}files/style.css" /><link href="favicon.ico" rel="shortcut icon" type="image/x-icon" />
    <style type='text/css'>
        .cat2-bg {
            background: #e74c3c;
        }

        .cat3-bg {
            background: #2ecc71;
        }

        .cat7-bg {
            background: #f39c12;
        }

        .cat4-bg {
            background: #3498db;
        }

        .cat1-bg {
            background: #6CC835;
        }

        .sub-menu li a:hover {
            background-color: #6CC835 !important;
            color: #ffffff !important;
        }

        .flex-direction-nav {
            display: none !important;
        }

        .createdby {
            direction: rtl;
        }
    </style>
    <script type="text/javascript">
        $(document).ready(function () {
            $('#weatherWidget').weatherfeed(['20070291'], {
                unit: 'c',
                woeid: true
            });
        });

       
    </script>
    
    <style>
        .attachment-wt175_115 {
            height: 70px !important;
        }
    </style>
</head>
<body>
   







<script src="{{this}}files/MicrosoftAjax.js" type="text/javascript"></script>
<script src="{{this}}files/MicrosoftAjaxWebForms.js" type="text/javascript"></script>
<script src="{{this}}files/jquery-te-1.4.0.min.js" type="text/javascript"></script>
<script src="{{this}}files/jquery-ui.min.js" type="text/javascript"></script>
<script src="{{this}}files/jquery.js" type="text/javascript"></script>
<script src="{{this}}files/comment-reply.js" type="text/javascript"></script>
<script src="{{this}}files/custom.js" type="text/javascript"></script>
<script src="{{this}}files/hoverIntent.js" type="text/javascript"></script>
<script src="{{this}}files/html5.js" type="text/javascript"></script>
<script src="{{this}}files/jflickrfeed.min.js" type="text/javascript"></script>
<script src="{{this}}files/jquery-migrate.min.js" type="text/javascript"></script>
<script src="{{this}}files/jquery.flexslider-min.js" type="text/javascript"></script>
<script src="{{this}}files/jquery.mobilemenu.js" type="text/javascript"></script>
<script src="{{this}}files/jquery.mousewheel.min.js" type="text/javascript"></script>
<script src="{{this}}files/jquery.touchSwipe.min.js" type="text/javascript"></script>
<script src="{{this}}files/lightbox.min.js" type="text/javascript"></script>
<script src="{{this}}files/superfish.js" type="text/javascript"></script>
<script src="{{this}}files/wt-rating.js" type="text/javascript"></script>
<script src="{{this}}files/jquery.ticker.js" type="text/javascript"></script>

        <script type="text/javascript">
//<![CDATA[
Sys.WebForms.PageRequestManager._initialize('ctl00$ctl14', 'mainForm', [], [], [], 90, 'ctl00');
//]]>
</script>

        <div id="container" class="hfeed">
            <header id="header">
                <div class="top">
                    <div class="inner-wrap">
                        <div class="top-menu">
                            <div style="width: auto; color: white; font-size: 19pt; font-weight: 900">
                                الخليج لطاقة المستقبل
                            </div>
                        </div>
                        <div class="social">
                            <ul class="list">
                                <li><a href="https://twitter.com/FutureGulf" id="twitter" class="twitter" target="_blank"><i class="fa fa-twitter"></i></a></li>
                                <li><a href="https://www.facebook.com/gulffutureenergy" id="fb" class="fb" target="_blank"><i class="fa fa-facebook"></i></a></li>
                                <li><a href="https://www.linkedin.com/pub/gulf-future-energy/a6/126/a53" id="linkedIn" class="gplus" target="_blank"><i class="fa fa-linkedin"></i></a></li>
                                <li><a href="https://www.youtube.com/" id="youtube" class="youtube" target="_blank"><i class="fa fa-youtube-play"></i></a></li>
                            </ul>
                        </div>
                        <div class="lang-change">
                            <a id="lbEnglish" href="javascript:__doPostBack(&#39;ctl00$lbEnglish&#39;,&#39;&#39;)">English</a>
                            <span style="color:White;">|</span>
                            <a id="lbArabic" href="javascript:__doPostBack(&#39;ctl00$lbArabic&#39;,&#39;&#39;)">عربي</a>
                        </div>
                        <div class="lang-change">
                            
                                    <ul class="nav navbar-nav navbar-right">
                                        <li><a href="/admin">Log in</a></li>
                                    </ul>
                                
                        </div>
                    </div>
                </div>
                <div class="logo-wrap clearfix">
                    <div class="inner-wrap">
                        <div class="logo">
                            <h1>
                                <a href='/Home.aspx' title="Gulf Future Energy">
                                    <img src="/uploaded/avatars/1.png?1449556142" width="80px" />
                                </a>
                            </h1>
                        </div>
                        <div class="menu-section clearfix">
                            <nav id="main-menu">
                                <ul id="menu-menu-1" class="menu">
<li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-63">
     <a href="/page/8856/الرئيسيه">الرئيسيه</a>
 <ul>                          
                            
 </ul></li><li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-63">
     <a href="/page/8859/خدماتنا">خدماتنا</a>
 <ul>                          
                            
<li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-63">
     <a href="/page/8860/خدمات الطاقة الشمسية">خدمات الطاقة الشمسية</a>
</li><li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-63">
     <a href="/page/8861/طلب خدمة الطاقة الشمسية">طلب خدمة الطاقة الشمسية</a>
</li><li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-63">
     <a href="/page/8858/الاستشارات">الاستشارات</a>
</li><li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-63">
     <a href="/page/8876/حاسبة">حاسبة</a>
</li><li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-63">
     <a href="/page/8877/تدريب">تدريب</a>
</li> </ul></li><li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-63">
     <a href="/page/8878/مشاريعنا">مشاريعنا</a>
 <ul>                          
                            
<li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-63">
     <a href="/page/8879/المشاريع المحلية">المشاريع المحلية</a>
</li><li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-63">
     <a href="/page/8880/المشاريع الاقليمية">المشاريع الاقليمية</a>
</li><li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-63">
     <a href="/page/8881/المشاريع العالمية">المشاريع العالمية</a>
</li> </ul></li><li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-63">
     <a href="/page/8882/المنتجات">المنتجات</a>
 <ul>                          
                            
 </ul></li><li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-63">
     <a href="/page/8883/الاستوديو">الاستوديو</a>
 <ul>                          
                            
<li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-63">
     <a href="/page/8884/استوديو الصور ">استوديو الصور </a>
</li><li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-63">
     <a href="/page/8885/استوديو الفيديو">استوديو الفيديو</a>
</li> </ul></li><li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-63">
     <a href="/page/8886/الوظائف">الوظائف</a>
 <ul>                          
                            
<li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-63">
     <a href="/page/8887/الشواغر المتوفرة">الشواغر المتوفرة</a>
</li><li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-63">
     <a href="/page/8888/طلب وظيفة">طلب وظيفة</a>
</li> </ul></li><li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-63">
     <a href="/page/8889/شركاؤنا">شركاؤنا</a>
 <ul>                          
                            
 </ul></li><li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-63">
     <a href="/page/8890/اتصل بنا">اتصل بنا</a>
 <ul>                          
                            
 </ul></li><li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-63">
     <a href="/page/8891/عن الشركة">عن الشركة</a>
 <ul>                          
                            
<li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-63">
     <a href="/page/8892/الوثيقة الاستراتيجية">الوثيقة الاستراتيجية</a>
</li><li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-63">
     <a href="/page/8893/الهيكل التنظيمي">الهيكل التنظيمي</a>
</li><li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-63">
     <a href="/page/8894/إجراء الأعمال">إجراء الأعمال</a>
</li> </ul></li> 
     
                                </ul>
                            </nav>
                        </div>
                    </div>
                </div>

            </header>

            <script>
                jQuery(document).ready(function () {
                    jQuery("#feat-ticker").show();
                    jQuery("ul#ticker-posts").liScroll({ travelocity: 0.05 });
                });
            </script>
            <div class="inner-wrap">
                <div id="feat-ticker" class="section-title clearfix">

                    <div class="title">
                        <h4>
                            الأخبار</h4>
                    </div>
                    <ul id="ticker-posts" style="width: auto !important">
                         <li>
                                    <a href='/artical/8875/البدء في تركيب الأنظمة' rel="bookmark">
                                        البدء في تركيب الأنظمة</a>
                                    <div class="sep">&bull;</div>
                                </li>    
                    </ul>
                </div>
            </div>
            <!-- /newsticker -->  



            <div id="slider-section" class="clearfix">
                
    <script>
        jQuery(document).ready(function ($) {

            $(".slider").show();
            $('.slider').flexslider({
                slideshow: true,
                slideshowSpeed: 5000,
                mousewheel: false,
                keyboard: true,
                controlNav: false,
                directionNav: true,
                controlsContainer: ".slider .slider-nav",
                animation: "slide",
                itemWidth: 1400,
                itemMargin: 10,
                minItems: 1,
                maxItems: 1,
                move: 1,
            });
        });
    </script>
    <div class="inner-wrap">
        <div class="slider">
            <ul class="slides">
          <li>
                            <div class="thumb">
                                <a href='#' target="blank">
                                    <img style="width: 100%" height="320" src='/uploaded/slider/1435537292.jpg' class="attachment-wt270_320 wp-post-image" alt="10" />
                                </a>
                            </div>

                            <div class="post-info">
                                <div class="inner">
                                    <div class="post-header">
                                        <div class="title">
                                            <h2><a href='' target="blank">
                                               s1</a></h2>
                                        </div>
                                    </div>
                                    <div>
                                        
                                    </div>
                                </div>
                            </div>
                        </li><li>
                            <div class="thumb">
                                <a href='#' target="blank">
                                    <img style="width: 100%" height="320" src='/uploaded/slider/1435537305.jpg' class="attachment-wt270_320 wp-post-image" alt="10" />
                                </a>
                            </div>

                            <div class="post-info">
                                <div class="inner">
                                    <div class="post-header">
                                        <div class="title">
                                            <h2><a href='' target="blank">
                                               s2</a></h2>
                                        </div>
                                    </div>
                                    <div>
                                        
                                    </div>
                                </div>
                            </div>
                        </li>  
                        
                    
            </ul>
            <div class="slider-nav"></div>
        </div>
    </div>

            </div>
            <section id="main">
                <div class="inner-wrap">
                    <div id="content" class="featured-page">

                        
    <div id="endUserAboutUs">
        <div>
            <header class="cat-title">
                <h4 class="main-color-bg cat2-bg">
                    لماذا نحن ؟</h4>
            </header>
            <span class="imgHomeAboutUs">
                <img src="{{this}}files/WhyUsImage.jpg" /></span>
            <div id="home-whyUs">
                <p>
                        <ul>        <li> تأمين ما نسبته 100% من الطاقة الكهربائية اللازمة من الطاقة الشمسية.</li>        <li> المعدات والأجهزة ذات مواصفات عالمية معتمدة.</li>        <li> إشراف عالمي بتقنية عالية على التركيب.</li>        <li> خدمات بجودة عالية وزمن قياسي.</li>        <li> كفالة تركيب أنظمة شمسية شاملة طويلة الأمد ( محولات ولوحات شمسية).</li>        <li> توصيلات ذات تقنية عالية بنظام التحكم عن بعد وتركيب على نظام التجزئة.</li>        <li> خدمات صيانة بسواعد محلية وسريعة الاستجابة.</li>        <li> تقديم تسهيلات بنكية في حال طلب العملاء تمويل بنكي وتسهيلات بالدفعات.</li>    </ul>
                </p>
            </div>
        </div>
        <div id="divRSS">
            

<style type="text/css">
    .rssli {
        
    }
   .rssli .thumb,.rssli .thumb a,.rssli .thumb img {
         width: 200px !important;
         height: 150px !important;
          
     } 
   .rss-description {
       max-height: 300px;
       overflow: hidden;
   }
   .rss-description:hover {
       overflow-x: hidden;
       overflow-y: scroll;
   }
</style>
<div id="feat-carousel" class="carousel-section clearfix">
                        <script>
                            jQuery(document).ready(function ($) {
                                $(".carousel").show();
                                $('.carousel').flexslider({
                                    slideshow: true,
                                    slideshowSpeed: 4000,
                                    mousewheel: false,
                                    keyboard: true,
                                    controlNav: true,
                                    directionNav: false,
                                    controlsContainer: ".feat-carousel-nav",
                                    animation: "slide",
                                    itemWidth: 200,
                                    itemMargin: 15,
                                    minItems: 1,
                                    maxItems: 6,
                                    move: 1,
                                    reverse: true,
                                    pauseOnHover: true,
                                });
                            });
                        </script>
                        <div class="section-title clearfix">
                            <div class="title">
                                <h4 class="main-color-bg">Renewable Energy News</h4>
                            </div>
                            <div class="carousel-nav feat-carousel-nav"></div>
                        </div>

                        <div class="carousel">
                            <ul class="slides">
                                
                            </ul>
                        </div>
                    </div>
        </div>
    </div>

                    </div>


                    <!-- /sidebar -->

                    <div id="sidebar-right" class="sidebar">


                        <aside id="widgetLatestnews" class="widget widget_slider">
                            <div class="widget-title">
                                <h4 class="title">
                                    آخر الاخبار</h4>
                            </div>

                            <script>
                                jQuery(document).ready(function ($) {
                                    $(".sliderLatestNews").show();
                                    $('.sliderLatestNews').flexslider({
                                        animation: "slide",
                                        controlNav: true,
                                        slideshow: true,
                                        directionNav: false,
                                        slideshowSpeed: 6000,
                                        smoothHeight: false,
                                        keyboard: true,
                                        mousewheel: true,
                                    });
                                });
                            </script>

                            <div class="sliderLatestNews" style="min-height: 200px">
                                <ul class="slides">
                                         <li>
                                                <div class="thumb" style="background: #ffffff !important;">
                                                    <a href='/artical/8875/البدء في تركيب الأنظمة'>
                                                        <img src="/uploaded/news/1435540205.jpg" class="attachment-wt270_180 wp-post-image" alt="10" /></a>
                                                </div>
                                                <div class="excerpt-wrap">
                                                    
                                                    <h3><a href='/artical/8875/البدء في تركيب الأنظمة'>
                                                        البدء في تركيب الأنظمة </a></h3>
                                                </div>
                                            </li>     
                                </ul>
                            </div>

                        </aside>
                        <aside id="asideUsefulLink" class="widget widget_popular_categories" style="min-height: 150px">
                            <div class="widget-title">
                                <h4 class="title">
                                    روابط مفيدة</h4>
                            </div>
                            <ul class="list">
                                
                                        <li><span class='main-color-bg cat cat1-bg'></span><a href="http://www.arec-jo.com/ " target="blank">
                                            الهيئة العربية للطاقة المتجددة
                                        </a></li>
                                    
                                        <li><span class='main-color-bg cat cat1-bg'></span><a href="http://www.futureenergyusa.com/" target="blank">
                                            طاقة المستقبل
                                        </a></li>
                                    
                                        <li><span class='main-color-bg cat cat1-bg'></span><a href="http://www.safety-team.com/" target="blank">
                                            مجموعة الابداع الاستراتيجي
                                        </a></li>
                                    
                                        <li><span class='main-color-bg cat cat1-bg'></span><a href="http://www.kad3group.com/" target="blank">
                                            مجموعة كاد 3
                                        </a></li>
                                    
                                        <li><span class='main-color-bg cat cat1-bg'></span><a href="http://www.kostal-solar-electric.com/content/en/" target="blank">
                                            كوستال
                                        </a></li>
                                    
                                        <li><span class='main-color-bg cat cat1-bg'></span><a href="http://www.renesola.com/" target="blank">
                                            رينيسولا
                                        </a></li>
                                    
                                        <li><span class='main-color-bg cat cat1-bg'></span><a href="http://ec.europa.eu/energy/renewables/index_en.htm" target="blank">
                                            الهيئة الأوروبية للطاقة المتجددة
                                        </a></li>
                                    
                            </ul>
                        </aside>
                        <aside id="weather" class="widget widget_tag_cloud" style="min-height: 150px">
                            <div class="widget-title">
                                <div class="icon"></div>
                                <h4>&nbsp;</h4>
                            </div>
                            <div>
                                <div id="weatherWidget"></div>
                                
                            </div>
                        </aside>
                    </div>
                    <!-- /sidebar -->
                </div>
                <!-- /inner-wrap -->
                <div id="carousel-full" class="carousel-section clearfix">
                    
    <script>
        jQuery(document).ready(function ($) {
            $(".carousel-full").show();
            $('.carousel-full').flexslider({
                slideshow: false,
                slideshowSpeed: 3000,
                mousewheel: false,
                keyboard: true,
                controlNav: false,
                directionNav: true,
                controlsContainer: ".full-carousel-nav",
                animation: "slide",
                itemWidth: 80,
                itemMargin: 15,
                minItems: 2,
                maxItems: 10,
                move: 1,
            });
        });
    </script>
    <div class="inner-wrap">
        <div class="section-title clearfix">
            <div class="title">
                <h4 class="main-color-bg">
                    شركائنا</h4>
            </div>
        </div>
        <div class="carousel-full">
            <ul class="slides">
                
                        <li>
                            <div style="background: #ffffff" class="thumb">
                                <a href='http://www.kostal-solar-electric.com/content/de/index.php' target="blank" class="attachment-wt175_115">
                                    <img src='{{this}}files/1_KostalLogo.png' class=" wp-post-image" alt='كوستال' />
                                </a>
                            </div>
                        </li>
                    
                        <li>
                            <div style="background: #ffffff" class="thumb">
                                <a href='http://renesola.com/' target="blank" class="attachment-wt175_115">
                                    <img src='{{this}}files/2_renesola LOGO.jpg' class=" wp-post-image" alt='' />
                                </a>
                            </div>
                        </li>
                    
                        <li>
                            <div style="background: #ffffff" class="thumb">
                                <a href='http://www.kad3.com/' target="blank" class="attachment-wt175_115">
                                    <img src='{{this}}files/4_KAD3Logo.png' class=" wp-post-image" alt='' />
                                </a>
                            </div>
                        </li>
                    
                        <li>
                            <div style="background: #ffffff" class="thumb">
                                <a href='http://www.safety-team.com/' target="blank" class="attachment-wt175_115">
                                    <img src='{{this}}files/5_safty team logo.png' class=" wp-post-image" alt='' />
                                </a>
                            </div>
                        </li>
                    
            </ul>
        </div>
    </div>

                </div>
            </section>
            <!-- /main -->
            <footer id="footer">
                <div class="footer-widgets">
                    <div class="inner-wrap">
                        <div class="col-265">
                            <aside id="wellthemes_aboutus_widget-2" class="widget widget_aboutus">
                                <div class="social-links">
                                    <ul class="list">
                                        <li>
                                            <a href="https://twitter.com/FutureGulf" id="ftwitter" class="twitter" target="_blank"><i class="fa fa-twitter"></i></a>
                                        </li>
                                        <li>
                                            <a href="https://www.facebook.com/gulffutureenergy" id="ffb" class="fb" target="_blank"><i class="fa fa-facebook"></i></a>
                                        </li>
                                        <li class="linkedin">
                                            <a href="https://www.linkedin.com/pub/gulf-future-energy/a6/126/a53" id="flinkedin" class="linkedin" target="_blank"><i class="fa fa-linkedin"></i></a>
                                        </li>
                                        <li>
                                            <a href="https://www.youtube.com/" id="fyoutube" class="youtube" target="_blank"><i class="fa fa-youtube-play"></i></a>
                                        </li>
                                    </ul>
                                </div>
                            </aside>
                        </div>
                        <div class="col-265">
                            &nbsp;
                        </div>
                        <div class="col-265">
                            <aside id="text-2" class="widget widget_text">
                                <div class="widget-title">
                                    <h4>
                                        عن الشركة</h4>
                                </div>
                                <div class="textwidget">Gulf Future Energy. </div>
                            </aside>
                            <aside id="text-3" class="widget widget_text">
                                <div class="widget-title">
                                    <h4>
                                        البريد الالكتروني</h4>
                                </div>
                                <div class="textwidget">info@futureenergyusa.com </div>
                            </aside>
                        </div>

                        <div class="col-265 col-last">
                            <aside id="text-2" class="widget">
                                <div class="widget-title">
                                    <h4>
                                        عدد الزوار
                                    </h4>
                                </div>
                                <div align="center">
                                    
                                    <img src="http://www.e-zeeinternet.com/count.php?page=1083647&style=odometer&nbdigits=9" alt="Counter" style="height: 35px" border="0">
                                </div>
                            </aside>
                            <aside id="text-3" class="widget widget_text" style="padding-top: 18px">
                                <div class="widget-title">
                                    <h4>
                                        هذا الموقع تم إنشاؤه بواسطة</h4>
                                </div>
                                <div class="textwidget createdby">
                                    الاسم : Tariq Jibreen
                                </div>
                                <div class="textwidget createdby">
                                    البريد الالكتروني : tariqj86@hotmail.com
                                </div>
                                <div class="textwidget createdby">
                                    هاتف : 795928254 962+
                                </div>
                            </aside>
                        </div>
                    </div>
                </div>
                <div class="footer-info">
                    <div class="inner-wrap">
                        <div class="footer-left" style="float: left">
                            © الخليج لطاقة الستقبل
                        </div>
                    </div>
                </div>
            </footer>
        </div>
    </form>
</body>
</html>
