[include:"header_en"end include]
<div class="slider">
    <ul id="slider">        
        <li>
            <img width="2000" height="550" src="{{upload}}pages/[var:"pagedata[image_name]"end var]" class="attachment-full wp-post-image" alt="%slider_sql:title1e%">
        </li>		                           
    </ul>
    <div class="slider-overlay"></div>
</div>
<div class="main">
    <div class="home-section">
        <h3 class="page-title">[var:"pagedata[page_name]"end var]</h3>
        <div class="text">[var:"pagedata[page_cont]"end var]</div>                        
    </div>
</div>
[include:"footer_en"end include]                
