[include:"header_ar"end include]
<div id="inner-header">
    <img src="{{upload}}pages/[var:"pagedata[image_name]"end var]" alt ="" />
</div>


<div id="content">
    <div class="row-container visible visible-first">
        <div class="container-fluid">
            <div class="content-inner row-fluid">   
                <div id="component" class="span12">                   
                    <div class="page page-contact page-contact__">
                        <header class="page_header">
                            <h1 class="visible visible-first"><span class="item_title_part_0 item_title_part_odd item_title_part_first_half item_title_part_first item_title_part_last">
                                    [var:"pagedata[page_name]"end var]
                                </span></h1>
                        </header>
                        <article class="category_desc">
                            <div class="clr"></div>
                        </article>
                        <div class="items-row cols-1 row-0 row-fluid">
                            <div class="span12">
                                <!-- end item -->
                                [var:"pagedata[page_cont]"end var]	
                            </div><!-- end spann -->
                        </div><!-- end row -->


                    </div>
                </div>
            </div>
        </div>
    </div>
</div>







[include:"footer_ar"end include]                











